spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false

application:
  system:
    code: ${APPLICATION_SYSTEM_CODE}
  workshop:
    id: ${APPLICATION_WORKSHOP_ID}
  cors:
    allowed-origins: ${APPLICATION_CORS_ORIGINS}
  object-model:
    import:
      listener:
        enabled: ${APPLICATION_OBJECT_MODEL_IMPORT_LISTENER_ENABLED}
        kafka:
          topic: ${APPLICATION_OBJECT_MODEL_IMPORT_LISTENER_KAFKA_TOPIC}
  warehouse:
    state:
      marking:
        attrCodesListOfIntegers: ${MARKING_ATTR_CODES:93, 3565, 6726, 91}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:https://sso-test.dp.nlmk.com/auth}
  realm: ${KEYCLOAK_REALM:mes-rolling-dev}
  resource: ${KEYCLOAK_CLIENT:mes-rolling-warehouse-dev}
  bearer-only: true

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED}

mdm:
  enabled-mode: ${MDM_ENABLED}
  nsi:
    unit-attribute:
      topic: ${MDM_UNIT_ATTRIBUTE_TOPIC}
      enabled: ${MDM_UNIT_ATTRIBUTE_ENABLED}
    warehouse-place:
      topic: ${MDM_WAREHOUSE_PLACE_TOPIC}
      enabled: ${MDM_WAREHOUSE_PLACE_ENABLED}
    operation-type:
      topic: ${MDM_OPERATION_REFERENCE_TOPIC}
      enabled: ${MDM_OPERATION_REFERENCE_ENABLED}
    warehouse-unit-status:
      topic: ${MDM_WAREHOUSE_UNIT_STATUS_TOPIC}
      enabled: ${MDM_WAREHOUSE_UNIT_STATUS_ENABLED}
    unit-type:
      topic: ${MDM_WAREHOUSE_UNIT_TYPE_TOPIC}
      enabled: ${MDM_WAREHOUSE_UNIT_TYPE_ENABLED}
    unit-type-required-attribute:
      topic: ${MDM_WAREHOUSE_UNIT_TYPE_REQUIRED_ATTRIBUTE_TOPIC}
      enabled: ${MDM_WAREHOUSE_UNIT_TYPE_REQUIRED_ATTRIBUTE_ENABLED}
    slot:
      topic: ${MDM_WAREHOUSE_SLOT_TOPIC}
      enabled: ${MDM_WAREHOUSE_SLOT_ENABLED}


kafka-rest-proxy-settings:
  url: ${KAFKA_REST_SERVER:http://localhost:8082}
  username: ${KAFKA_REST_USER:test_user}
  password: ${KAFKA_REST_PASSWORD:test_password}

kafka-rest-proxy-topics:
  warehouse-state: ${WAREHOUSE_STATE_TOPIC:000-1.mes-cgp.cdc.stock-in-warehouse-test.0}

server:
  max-http-header-size: ${SERVER_MAX_HTTP_HEADER_SIZE}
