spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false

application:
  system:
    code: ${APPLICATION_SYSTEM_CODE}
  workshop:
    id: ${APPLICATION_WORKSHOP_ID}
  cors:
    allowed-origins: ${APPLICATION_CORS_ORIGINS}
  object-model:
    import:
      listener:
        enabled: ${APPLICATION_OBJECT_MODEL_IMPORT_LISTENER_ENABLED}
  warehouse:
    state:
      marking:
        attrCodesListOfIntegers: ${MARKING_ATTR_CODES:93, 3565, 6726, 91}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:https://sso-test.dp.nlmk.com/auth}
  realm: ${KEYCLOAK_REALM:mes-rolling-dev}
  resource: ${KEYCLOAK_CLIENT:mes-rolling-warehouse-dev}
  bearer-only: true

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED}

server:
  max-http-header-size: ${SERVER_MAX_HTTP_HEADER_SIZE}
